#端口号
server:
  port: 8130
  #服务名
spring:
  application:
    name: aliyun-oss
#环境
  profiles:
    active: dev
#oss
aliyunossfile:
  endpoint: oss-cn-beijing.aliyuncs.com
  key-id: LTAI4FwGnafnb9yxksw
  key-secret: e669dSjIO9ZQq3kEnSG75g8Ph
  bucket-name: online----edu
  file-host: avatar
