# 服务端口
server:
  port: 8140
  # 服务名
spring:
  application:
    name: online-ucenter
  profiles:
    active: dev   # 环境设置：dev、test、prod
  datasource:    # mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # Hikari是Spring Boot 2.0之后默认整合的数据库连接池，比druid更快的数据库连接池
    type: com.zaxxer.hikari.HikariDataSource   # 数据源类型
    hikari:
      pool-name: OnlineHikari    # 连接池名称，默认HikariPool-1
      maximum-pool-size: 12     # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      connection-timeout: 60000   # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      minimum-idle: 10    # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      idle-timeout: 500000  # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      max-lifetime: 540000  # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      connection-test-query: SELECT 1   #连接测试查询

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mapper xml文件的路径
  mapper-locations: classpath:cn/losemen/ucenter/mapper/xml/*.xml
#Eureka  服务器注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8220/eureka/
  instance:
    instance-id: online-ucenter  #修改默认描述
    #eureka服务器上获取的是服务器的ip地址，否则是主机名
    prefer-ip-address: true
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明
    #　　lease-renewal-interval-in-seconds 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“
    #　　lease-expiration-duration-in-seconds  告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10