# 服务端口
server:
  port: 8160
spring:
  # 服务名
  application:
    name: online-vod
  # 最大上传单个文件大小：默认1M
  servlet:
    multipart:
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  #阿里云 vod
  #不同的服务器，地址不同
aliyunvodfile:
  key-id: LTAI4FwGnafnb9yxksw
  key-secret: e669dSjIO9ZQq3kEnSG75g8PhZ

